[MeristShredderFix.X2Effect_ShredderFix]

; If `true`, any weapon category not present in InvalidWeaponCategories will be considered valid
bApplyToAnyWeaponCategory = false

; Ignored if the previous option is `true`
; If not empty, only the weapon categories persent in the array will be considered valid
; If empty, any weapon category not present in InvalidWeaponCategories will be considered valid
+ValidWeaponCategories = "pistol"
+ValidWeaponCategories = "sidearm"
+ValidWeaponCategories = "sawedoffshotgun"

; If `bApplyToAnyWeaponCategory` is `false` or if `ValidWeaponCategories` is empty,
; any weapon category not present in this array will be considered valid
; +InvalidWeaponCategories = "sword"
; +InvalidWeaponCategories = "wristblade"
; +InvalidWeaponCategories = "gauntlet"

; If `true`, will apply to any valid weapon category regardless of the slot
bApplyToAnySlot = false

; If the previous option is `false`, will only apply to the following slots
+ValidInventorySlots = eInvSlot_PrimaryWeapon

; The amount of shred specific non-standard weapon tech levels should have
+ShredderPerWeaponTech=(WeaponTech = "laser_lw",    Shred = 1)
+ShredderPerWeaponTech=(WeaponTech = "coilgun_lw",  Shred = 2)

+ShredderPerWeaponTech=(WeaponTech = "alien",       Shred = 1)
+ShredderPerWeaponTech=(WeaponTech = "laser",       Shred = 1)
+ShredderPerWeaponTech=(WeaponTech = "coil",        Shred = 2)
+ShredderPerWeaponTech=(WeaponTech = "coil_lw",     Shred = 2)
+ShredderPerWeaponTech=(WeaponTech = "lw_magnetic", Shred = 2)
+ShredderPerWeaponTech=(WeaponTech = "lw_coil",     Shred = 2)
+ShredderPerWeaponTech=(WeaponTech = "lw_beam",     Shred = 3)

; If `true`, the "primary Shredder" fix will be applied to any damage class
bApplyPrimaryFixToAnyEffectClass = false

; Ignored if the previous option is `true`
; If the damage effect is not X2Effect_Shredder and is not X2Effect_ApplyWeaponDamage,
; the "primary Shredder" fix will only be applied if the class is present in the array
; +ValidEffectClasses = "X2Effect_DLC_3StrikeDamage"
; +ValidEffectClasses = "X2Effect_ArcWaveMultiDamage"

[MeristShredderFix.X2DLCInfo_MeristShredderFix]

; If `true`, removes the "primary Shredder" fix added in Weapon Fixes by Mr. Nice
bRemoveWeaponFixesEffect = true

; If `true`, removes the weapon tech fix added in LWOTC by Zelfana
bRemoveLWEffect = true