[MeristShredderFix.X2DLCInfo_MeristShredderFix]
DLCIdentifier = "MeristShredderFix"

[MeristShredderFix CHModDependency]
DisplayName = "MeristShredderFix"

; +IncompatibleMods="WepUpgradeFix"

[MeristShredderFix CHDLCRunOrder]
+RunAfter = LongWarOfTheChosen
+RunAfter = WepUpgradeFix

; RunPriorityGroup = RUN_FIRST
; RunPriorityGroup = RUN_STANDARD
; RunPriorityGroup = RUN_LAST